exclude: ['./readme.md']
exclude: ['*.scss']
timezone: Australia/NSW
defaults:
    -
    scope:
      path: ""
    values:
      layout: "default"

    -
    scope:
      path: "resources"
    values:
      image: "true"
  

permalink: /posts/:author/:categories/:year/:month/:day/:title/